turning in assignment
stephhappens/05-flex-practice pull request #1
Opened 2016-10-03 21:34 UTC by stephhappens

2016-10-09 20:38 UTC, rtablada requested changes
Currently missing the sticky footer using display flex and flex-direction column.

2016-10-10 13:21 UTC, rtablada requested changes
I need to pick back up and figure out other things to include with this review. But review the Rock Solid Layout docs in TIYO and that should help with the grid and containers.

2016-10-10 13:21 UTC, rtablada commented on public/index.html
> +          <h1 class="nav-group nav-group__item">BACON SO HOT RIGHT NOW</h1>
I usually will separate the grouping of left and right to make more sense semantically and to make life easier (this helps for flex or float based navbars).

2016-10-10 13:21 UTC, rtablada commented on public/index.html
> +      <div class="hero__container-absolute">
To position the text within this centered using position: absolute, you will need a parent element that will be position relative and a child element that is position absolute.

2016-10-10 13:21 UTC, rtablada commented on public/index.html
> +          <h1 class="nav-group nav-group__item">BACON SO HOT RIGHT NOW</h1>
Also, the navbar contents should be contained to a max-width for large screens

2016-11-01 21:47 UTC, stephhappens commented
* [ ] Create a new project called `05 Flex Practice` using `yo sass-broccoli`
* [ ] Use the `git` cli to initialize a new project
* [ ] Use `hub create` to create a new repository on github called `02-box-model`
* [ ] Use the `git` cli to create a branch called `develop`
* [ ] Checkpoint: Change `title` for page
* [ ] Use `hub pull-request -m "Turning in assignment"` to create a new pull request
* [ ] Post link to pull request on online.theironyard.com
  * [ ] Checkpoint: Nav Bar
    - [ ] HTML
    - [ ] Styling
  * [ ] Checkpoint: Flexbox hero
    - [ ] HTML
    - [ ] Styling
  * [ ] Checkpoint: Position absolute hero
    - [ ] HTML
    - [ ] Styling
  * [ ] Checkpoint: Grid
    - [ ] HTML
    - [ ] Styling
  * [ ] Checkpoint: Card
    - [ ] HTML
    - [ ] Styling
  * [ ] Checkpoint: Footer
    - [ ] HTML
    - [ ] Styling

2017-03-30 02:35 UTC, merged